[project]
name = "analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "jax>=0.5.2",
    "matplotlib>=3.10.1",
    "msgpack>=1.1.0",
    "numpy>=2.2.3",
    "shapely>=2.0.7",
]
